language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
before_install:
  - gem install bundler
env:
  global:
addons:
  code_climate:
    repo_token: 08219ed943b69ed2db93fc18ecd00f72f6dabc4cdb9792e22a731c0ff2c2b818
matrix:
  include:
    - rvm: 2.3.8
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails_4.2.gemfile
