language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - ruby-head
gemfile:
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
before_install:
  - gem install bundler
env:
  global:
#    - FOG_PROVIDER=AWS
matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_4.0.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
